name: patwari_mock_test_app
description: Patwari 2025 Mock Test - Offline App
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  percent_indicator: ^4.2.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/